USE ocp6;

-- Vérifier si la table COMMENT existe, si oui, effacer tout son contenu

DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS POST;
DROP TABLE IF EXISTS SUBSCRIPTIONS;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS TOPIC;